### ISSUE TITLE
Couple of area codes wrong in covid-19-cases-uk.csv

### ISSUE THREAD

**Issue by timday** [tomwhite/covid-19-uk-data#11]
Noticed a couple of oddities in the file in the course of processing it.  Not looked at the details of how you're pulling the data at all, so I've no idea if this is an "upstream" issue you can do nothing about (and even if it was, whether your tools should be aiming to clean such things up or just present things "as is").  I'm looking at the 2020-03-22 update of `covid-19-cases-uk.csv`.

Both Orkney and Lothian have area code `S08000024`.  But Orkney should be `S08000025`.
```
2020-03-02,Scotland,S08000024,Lothian,0
2020-03-02,Scotland,S08000024,Orkney,0
```

Both Tayside and Western Isles have area code `S08000030`.  But Western Isles should be `S08000028`.
```
2020-03-01,Scotland,S08000030,Tayside,0
2020-03-01,Scotland,S08000030,Western Isles,0
```

I note there are only 5 records for Orkney and Western Isles (2020-03-01 - 2020-03-05) c.f the full 22 for Tayside and Lothian.

Easily enough fixed-up when importing the data but thought it worth bringing to your attention.

**Comment by tomwhite** [comment]
@timday thank you for bringing this to my attention. The errors were introduced in #0331ef124b992f2940d840f568120671d4bf5294 when importing some older data. I generate the area codes from the health board names, so it's appropriate to fix them here.
