### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by jowers** [tomwhite/covid-19-uk-data#13]
Hey, thanks for putting this together - it's really useful to have the historical data, not just the current day's figures.

I noticed a couple of discrepancies in the data:

* The daily stats for Barking and Dagenham are missing for the last couple of days.
* `data/covid-19-cases-uk.csv` is missing the data for English areas for 21st March

For the first of these, I noticed that Barking is the first Area on the csv file downloaded from arcgis.com so wondered if there is something stripping the first data row? I don't have the data for 22/3, but today's value is 42 if that helps.

**Comment by tomwhite** [comment]
@jowers thank you for reporting this. As you surmised the code was stripping the first row, assuming it was a header. I've added the header in and fixed the data.
