### ISSUE TITLE
Add a check for data gaps

### ISSUE THREAD

**Issue by tomwhite** [tomwhite/covid-19-uk-data#14]
Check no days are missing

**Comment by timday** [comment]
Don't know about gaps, but what happened on 2020-03-20?  The England case numbers all seem to be exactly the same as they were on the day before (2020-03-19).  But Scotland's numbers did update on the 20th.  Noticed it while plotting this ghastly crime against eyeballs:
![cases-log](https://user-images.githubusercontent.com/230848/77912808-24b3b880-728b-11ea-9639-4ca599a8c4ed.png)
A glance at the https://www.arcgis.com/apps/opsdashboard/index.html#/f94c3c90da5b4e9f9a0b19484dd4bb14 seems to show no hiatus in the curve's progress so it's not like there was no England data at all that day (unless they've done what I'm contemplating doing and fudged it with interpolated data for that day).

**Comment by tomwhite** [comment]
@timday thanks for reporting this - it looks like the file wasn't updated, or I downloaded an old one for that day. The good news is that PHE is publishing historical data now, so I can update it from there.

**Comment by tomwhite** [comment]
Fixed the issue for 20 March (and a similar one for 12 March) here: c46235f93c42812b7616e148a731e8f10ef29095

**Comment by timday** [comment]
I note Northern Ireland data has started appearing (which is great).  But there's 26th & 27th... and then a gap for the 28th&29th, and then the 30th is present again.  No Northern Ireland data at the weekend?  Or just early-days glitches as the reporting operation ramps up?

**Comment by tomwhite** [comment]
It's for weekdays only - the report is shorter at the weekend.

**Comment by robchallen** [comment]
I notice a couple of days missing in a few regions - e.g. Hartlepool has no data on 30th April and 1st May. This is an upstream issue, and I've reported it to PHE. Hopefully when they fix it you can recover

https://github.com/PublicHealthEngland/coronavirus-dashboard/issues/153#issue-611739857

**Comment by tomwhite** [comment]
Thanks for reporting upstream @robchallen. This repo syncs with the complete upstream history every day, so it will be reflected here when it's fixed by PHE.

**Comment by robchallen** [comment]
PHE has responded with a wont fix. their rationale is that missing values imply no change from previous day, and this is an upstream issue for them too (sigh). I can adapt my pipeline to this but will probably impact others:

https://github.com/PublicHealthEngland/coronavirus-dashboard/issues/153#issuecomment-623406300

WDYT?

**Comment by tomwhite** [comment]
OK, sounds like it's a thing downstream analyses need to handle. This repo should change the data as little as possible.
