### ISSUE TITLE
Potential wrong data import

### ISSUE THREAD

**Issue by covid19viz** [tomwhite/covid-19-uk-data#16]
For 26.03.2020 there seems to be a problem on data import, since Swansea Bay and Powys data are switched. Please review the import process...
Also, by chance, any idea if someone has created a population dataset or lookup for the reported areas that I can use?
I would like to use your data into my data visualization, if I can match the data with proper population figures:
https://covid19viz.github.io

**Comment by tomwhite** [comment]
Thanks for reporting this. Fixed in https://github.com/tomwhite/covid-19-uk-data/commit/4c3220f4a37c69400b8d7f884ee1a36a30ac410a

I've opened #18 for the question about population data - I agree it would be handy to have a dataset for this.
