### ISSUE TITLE
Dashboard of Welsh Covid-19 data

### ISSUE THREAD

**Issue by andrewroberts** [tomwhite/covid-19-uk-data#21]
I have taken [Amit Agarwal's dashboard for Indian data](https://docs.google.com/spreadsheets/d/1swdjquWqq5tjMm9tpxMa-9C8rjCyWVWHs-ODdAXfWDw/edit#gid=936573058), and [repurposed it for Wales using your data](https://docs.google.com/spreadsheets/d/109sUBWwlOwjX4K7LvGsOHcbBKxLJfz9ReJdoKSD804s/edit#gid=936573058).

Thanks for effort in putting this together.

**Comment by tomwhite** [comment]
Thanks for sharing! Is there a way to scale the sparklines so they can be compared (e.g. to show Aneurin Bevan has many more cases than the others)?

**Comment by andrewroberts** [comment]
You can do. I tried it but then some of the other graphs pretty much dissappeared compared to Aneurin Bevan.

**Comment by tomwhite** [comment]
Maybe that's the point? Depends a bit on what you are trying to show - both are valid, so it might be useful to have two sparklines for each health board, one to show the trend relative to itself, the other relative to other HBs.
