### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by harrier07** [tomwhite/covid-19-uk-data#22]
Thank you all for the work that has gone into compiling the government data and making it easily machine readable. It is proving invaluable for contingency planning at a local level and comparing the outbreak here in the UK to those elsewhere. I just wanted to let you know that by contributing you are providing a valuable service to your country and it is really appreciated. I'm new to git hub but have been able to pull the data automatically into a basic google sheets file for local level planning. That is the kind of user you are helping immensely. Keep up the good work!

**Comment by tomwhite** [comment]
@harrier07 thanks for the kind words. I'm glad you are finding it useful!
