### ISSUE TITLE
NHS England daily deaths by trust and region

### ISSUE THREAD

**Issue by tomwhite** [tomwhite/covid-19-uk-data#30]
Historical data being published in XLSX here: https://www.england.nhs.uk/statistics/statistical-work-areas/covid-19-daily-deaths/

**Comment by nanjizal** [comment]
do you want pull request.. see https://github.com/tomwhite/covid-19-uk-data/issues/19

**Comment by tomwhite** [comment]
I opened this just to document the source of data. It's easy to consume the data from the NHS website (XLSX is machine readable), so I'm not planning on adding it to this repo.
