### ISSUE TITLE
No Data for Indicators for England for 08/04/2020

### ISSUE THREAD

**Issue by Jcamain** [tomwhite/covid-19-uk-data#32]
Just to let you know the English figures haven't come in for yesterday - also there is some discrepancy with overall English figures, I'll have a look as I think I know what it is, but need to check first :-)

**Comment by Jcamain** [comment]
The discrepancy is that in your csv file for the whole of the UK, 'data/covid-19-cases-uk.csv ', doesn't add up to the same value as in the Public Health England spreadsheet - they have included an 'unconfirmed' value that is included in their calculations in their sheet 'UTLA's' - don't think this is in your data set?  This is anyone where they don't have a post code and therefore can't link it to a UTLA.

**Comment by tomwhite** [comment]
Thanks for reporting @Jcamain, this should be fixed now.

**Comment by Jcamain** [comment]
Thanks!  Also, not sure if you can do anything about the England 'Unconfirmed' values? - it should have come through on the UTLA sheet from the Public Health Spreadsheet?
