### ISSUE TITLE
Crawl data from new PHE dashboard

### ISSUE THREAD

**Issue by tomwhite** [tomwhite/covid-19-uk-data#38]
The new PHE dashboard at https://coronavirus.data.gov.uk/ has data for
* UK, England, Scotland, Wales, NI cases
* UK, England, Scotland, Wales, NI deaths
* English region cases
* English UTLA cases

Plus historical data for all of these.

There are CSV links, but the page is dynamically generated HTML. So it might be easier to pull data from the underlying JSON feed, see https://github.com/PublicHealthEngland/coronavirus-dashboard/blob/master/src/hooks/useLoadData.js.

Also discussed here: https://twitter.com/DavidBeavan/status/1250454570070933504

**Comment by slowe** [comment]
@tomwhite I've commented on their Github repo and sent an email to the feedback email. I will also point this out to some lovely NHS Digital folks who shall hopefully be in the [#OpenDataSavesLives Zoom call at 11am](https://odileeds.org/projects/open-data-saves-lives/covid19/). I think having fixed URLs is an important thing. I will push to get whoever is currently publishing the new JSON to mirror the latest version at a fixed URL. URLs are fundamental building blocks of the web. Nobody can currently link to the "latest" version of the data.

**Comment by tomwhite** [comment]
@slowe totally agree. Thanks for raising this with the appropriate people!
