### ISSUE TITLE
Scotland rows are showing NaN in covid-19-cases-uk.csv

### ISSUE THREAD

**Issue by neatdot** [tomwhite/covid-19-uk-data#44]
Scotland rows in the covid-19-cases-uk.csv file are showing NaN for 2020-03-07:

`

2020-03-07 | Scotland | S08000015 | Ayrshire and Arran | NaN
-- | -- | -- | -- | --

`

**Comment by tomwhite** [comment]
I've started syncing the historical case numbers by area from the official source at https://www.gov.scot/publications/trends-in-number-of-people-in-hospital-with-confirmed-or-suspected-covid-19/. Numbers less than 5 are denoted by * in that spreadsheet, and I represent them as NaN in the CSV file. You probably need to treat them specially in your processing pipeline.

**Comment by neatdot** [comment]
Got you. I've already adopted something similar for the "1 to 4" ranges. Thanks for the response.
