### ISSUE TITLE
Number of tests by pillars

### ISSUE THREAD

**Issue by LoryPack** [tomwhite/covid-19-uk-data#53]
Hi, thank you very much for the amazing work! I was wondering if it is possible to add a break of the total number of tests (and confirmed cases as well) by the testing "pillars" strategy. Right now, the government webpage https://www.gov.uk/guidance/coronavirus-covid-19-information-for-the-public reports that daily, but I don't know how far back in time this was true, and if it is possible to retrieve that info from the past. Also, I don't know if that kind of data is released at the Englad/Wales/Scotland/NI level. 

Do you think this is possible, or do you know of any source collecting this kind of data? 

Thanks!

**Comment by tomwhite** [comment]
This is a good idea. The webpages are checked into this repo every day, so we could go through and extract the historical pillar information (it goes back about a month). I've been meaning to do it, but have been hoping that PHE or DHSC would just publish the data in machine readable form (which they've said they will, but no timescale).

**Comment by LoryPack** [comment]
Thank you. I think I will try to add that to the UK csv, as I don't think pillar data is available for the countries. I had a look at your pipeline and I think I understand more or less what is going on. I think I will need to modify `parse_totals` and `save_indicators_to_sqlite` in `tools/parsers.py` and `convert` in `convert_sqlite_to_csvs.py`. Do you think that is it, or am I missing something?

**Comment by tomwhite** [comment]
Hi @LoryPack - thanks for the offer! I actually wrote most of this a couple of days ago but haven't merged it yet. See https://github.com/tomwhite/covid-19-uk-data/compare/testing-pillars?expand=1. You can see the extra pillar information in there. Let me know what you think.

**Comment by LoryPack** [comment]
That looks amazing, it is definitely better than anything I would have been able to do! Thank you very much!

**Comment by tomwhite** [comment]
Thanks @LoryPack! I've now merged this, and all the pillar data is in this file: https://raw.githubusercontent.com/tomwhite/covid-19-uk-data/master/data/covid-19-tests-uk.csv

I hope people do interesting things with this data!
