### ISSUE TITLE
covid-19-cases-uk no data on 05-29 for NI

### ISSUE THREAD

**Issue by deckzero** [tomwhite/covid-19-uk-data#59]
Hi Tom,

Thank you so much for updating the covid-19 data - we retrieve it everyday to update our regional Rz (estimated R) heatmap. We just found that there is no NI data in the file for 29 May. I think this is because the date for 05-29 data was recorded as 05-30 - would you mind take a look at it please? As of now, PHA NI has not published 05-30 data as yet. We've checked that all other dates are consistent with the official reported data except for this latest date.

Thanks again. 

Best wishes
Deckzero

**Comment by tomwhite** [comment]
Hi @deckzero - thanks for reporting the problem, it should be fixed now.
