### ISSUE TITLE
I have experimented with rendering your csv data.

### ISSUE THREAD

**Issue by nanjizal** [tomwhite/covid-19-uk-data#6]
I have experimented with rendering your csv data with canvas, you can read details of setting up if you wish to experiment with the code, you can view current online test and see the simple visual from the readme:  
  
[https://github.com/nanjizal/covid19/blob/master/README.md](https://github.com/nanjizal/covid19/blob/master/README.md)  

Obviously more interesting renders could be created, but had to find lat/long conversion code which I ported, test and fix my low level csv parser and find lat/long data for the e number areas, related links are commented within code.  If you want direct link to your repo data on readme please let me know, or if interested in further collaboration. I can also with more effort render in webgl with some depth or with svg, since I use haxe can also create mobile/desktop versions, using openfl, kha or heaps time permitting.

**Comment by tomwhite** [comment]
Hi @nanjizal, thanks for letting me know about your visualization. Have you tried a time lapse animation, or a way of adjusting the date, to see how the number of cases change?

**Comment by nanjizal** [comment]
Tom

I have updated it, it now does very simple animation and feeds off your git raw so automatically uses latest data, probably next weekend I will look to improve the visual significantly.

We should talk about improving the data with a tool that checks the file adds lat, long, os north, os east and fixes place names and e areas etc.. I currently have to do a lot of this sort of stuff, and quite a few hacks to get all the points to render.  Not sure but really would be nice to break down some locations like York into their e areas, maybe there is another way to get more fine data? Do you have death and recovered data? 

Would be nice to also look at mapping other countries, I can provide code to help with cleaning data and more types of graphs, platforms etc.., perhaps you could look at how we might get data for other countries?

Also I need to find a way to indicate when data was last updated via code.

Best

Justin

**Comment by nanjizal** [comment]
Will look to add credit to the page and links to your repo, as I try to refine the general look and feel, mainly only have proper time at weekends, I would love to extend project to other locations.  Have you looked at git actions maybe you can automate your scripts?

**Comment by timday** [comment]
Just going to use this thread to dump a few artefacts produced from mashing up area virus case-counts with other area stats....

Areas' case-count growth rate over the last few days vs. area's old-age demographics, using 2011 census:
![oldies-all](https://user-images.githubusercontent.com/230848/77797470-04a4af00-7069-11ea-9f37-94b2cf5b258d.png)
Doesn't seem to be much correlation at all.  Surprising.  Have looked at different age thresholds but this is as good as it gets.

Areas's case-count growth rate over the last few days vs. area's Leave vote in the 2016 referendum:
![brexit-all](https://user-images.githubusercontent.com/230848/77797678-6238fb80-7069-11ea-9e12-7ecc5645c839.png)
A bit more correlation!  (Correlation not causation of course.  But... what's the explanation if it's not demographics?)

And - no virus connection, but just to complete the set - area's Leave vote in the 2016 referendum vs area's old-age demographics, using 2011 census:
![oldies-vote-all](https://user-images.githubusercontent.com/230848/77797845-b3e18600-7069-11ea-8426-60ed2e6ebcef.png)
No surprise there; I think the demographics of the Leave vote are well documented.

**Comment by timday** [comment]
Took a look at virus case growth rate vs the various deprivation indices from https://www.gov.uk/government/statistics/english-indices-of-deprivation-2019 .  Just for England areas.

Most correlated index vs. last week's area virus case-count growth rates seemed to be "Education, Skills and Training":
![deprivation-Education](https://user-images.githubusercontent.com/230848/77821233-71a75b80-70e0-11ea-9117-a748aa120ff7.png)
Higher score = more deprived; 5 highest/lowest scoring areas:
```
  Highest
    Knowsley                        : 41.89
    Kingston upon Hull, City of     : 41.67
    Doncaster                       : 39.72
    Stoke-on-Trent                  : 38.94
    Blackpool                       : 38.50
  Lowest
    Richmond upon Thames            : 3.53
    Kensington and Chelsea          : 5.19
    Wokingham                       : 6.22
    Wandsworth                      : 6.65
    Kingston upon Thames            : 6.94
```

Next most correlated one was "Health Deprivation and Disability":
![deprivation-Health](https://user-images.githubusercontent.com/230848/77821280-d19e0200-70e0-11ea-95ed-6af005ff909b.png)
5 highest/lowest scoring areas (although in this case these highest scoring areas aren't actually high case-count growth rates, but it gives the flavour of what sort of places score highly on this index):
```
  Highest
    Blackpool                       : 1.64
    Knowsley                        : 1.38
    Liverpool                       : 1.35
    Manchester                      : 1.20
    St. Helens                      : 1.07
  Lowest
    Wokingham                       : -1.54
    Richmond upon Thames            : -1.37
    Kensington and Chelsea          : -1.24
    Buckinghamshire                 : -1.10
    Barnet                          : -1.07
```

Neither of these as good a fit as that 2016 Leave % vote though (r=0.34 for England only with latest data).

**Comment by nanjizal** [comment]
<img width="460" alt="ukCovid19bg" src="https://user-images.githubusercontent.com/20134338/77823200-22b5f200-70f1-11ea-8382-10eededf1a9d.png">

I have added a background, I originally created by hand in flash to keep vectors points low, extracted to arrays of points in 'uk' repo, I don't think the outline mapping is perfect but close enough, manually adjust scale position to match similar image mapping. The curved grid lines are drawn from looping lat/long so relate well to plotted data. Still all MIT.

**Comment by timday** [comment]
Looked at some interesting "health indicators" available by UTLA at https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/healthinequalities/datasets/indicatorsoflifestylesandwidercharacteristicslinkedtohealthylifeexpectancyinengland (2017 release of ~2015 data)

The last-week's cases growth rate vs. obesity rate is the most correlated and quite striking:
![obesity](https://user-images.githubusercontent.com/230848/77827675-f7420000-710e-11ea-9534-6362c9788e2b.png)

r-value vs. other "indicators":
```
Correlations, highest to lowest (absolute)
  Obesity rate (%)                                  : 0.349
  Physically active adults (%)                      : -0.218
  Alcohol-related admissions (per 100,000)          : 0.180
  Adults eating 5-a-day (%)                         : -0.175
  Employment rate (%)                               : -0.173
  Economically inactive (%)                         : 0.157
  Unemployment rate (%)                             : 0.156
  Preventable Mortality (deaths per 100,000)        : 0.143
  Smoking prevalence (%)                            : 0.023
```

**Comment by nanjizal** [comment]
I have moved the latitude aspect of the code to a separate repo, the demo used is Canvas but since it's haxe the demo could be reworked for other haxe targets like OpenFL and used on mobile as c++.
https://github.com/nanjizal/latLongUK
