### ISSUE TITLE
England is not the UK

### ISSUE THREAD

**Issue by richardreeve** [tomwhite/covid-19-uk-data#9]
It’s great that you’re doing this, but I notice that the links from the README for England are to the UK csv, and the England csv is pretty sparse - you could generate it automatically from UK minus other countries if you don’t have any other source... ?

**Comment by tomwhite** [comment]
@richardreeve thanks for reporting the issue. I've fixed the link.

There is no source for England's number of tests and deaths that I know of. Also we don't have test numbers for Wales, so we could only fill in England deaths I think.

**Comment by tomwhite** [comment]
BTW I filled in the historical number of deaths for England here: eff6e61cd03343e445ef7dd1433a8f3fcee002b9.

I'm reopening this issue as I'm working on filling in missing case numbers for England.

**Comment by tomwhite** [comment]
Filled in older case numbers here: 0e10600b9e4754962931173453ceac499bd993d5
